---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - config/apps.yml
  roles:
    - elliotweiser.osx-command-line-tools
    # https://github.com/elliotweiser/ansible-osx-command-line-tools
  tasks:
    - name: Install packages
      import_tasks: install_apps.yml
    - name: Configure OSX
      import_tasks: setup_osx.yml